version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:latest
    depends_on: 
      - mysql
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports: 
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html   
    networks:
      - wordpress-network    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports: 
      - "8081:80"  
    networks:
      - wordpress-network   

volumes:
  mysql_data:
  wordpress_data:

networks:
  wordpress-network :
    driver: bridge