apiVersion: apps/v1
kind: Deployment
metadata: 
    labels: 
      app: mongo
    name: mongo-deployment
spec: 
    replicas: 1
    selector: 
      matchLabels: 
       app: mongo

    template: 
     metadata: 
       labels: 
        apps: mongo
     spec: 
      containers:
      - name: mongo-pods
        image: mongo
        ports:
        - containerPort: 27017